.PHONY: clean All

All:
	@echo "----------Building project:[ FIbonacci - Debug ]----------"
	@cd "FIbonacci" && "$(MAKE)" -f  "FIbonacci.mk"
clean:
	@echo "----------Cleaning project:[ FIbonacci - Debug ]----------"
	@cd "FIbonacci" && "$(MAKE)" -f  "FIbonacci.mk" clean
