.PHONY: clean All

All:
	@echo "----------Building project:[ THE_GCD_Function - Debug ]----------"
	@cd "THE_GCD_Function" && "$(MAKE)" -f  "THE_GCD_Function.mk"
clean:
	@echo "----------Cleaning project:[ THE_GCD_Function - Debug ]----------"
	@cd "THE_GCD_Function" && "$(MAKE)" -f  "THE_GCD_Function.mk" clean
