.PHONY: clean All

All:
	@echo "----------Building project:[ Permutations - Debug ]----------"
	@cd "Permutations" && "$(MAKE)" -f  "Permutations.mk"
clean:
	@echo "----------Cleaning project:[ Permutations - Debug ]----------"
	@cd "Permutations" && "$(MAKE)" -f  "Permutations.mk" clean
