.PHONY: clean All

All:
	@echo "----------Building project:[ Easy_Sum_Set_Problem - Debug ]----------"
	@cd "Easy_Sum_Set_Problem" && "$(MAKE)" -f  "Easy_Sum_Set_Problem.mk"
clean:
	@echo "----------Cleaning project:[ Easy_Sum_Set_Problem - Debug ]----------"
	@cd "Easy_Sum_Set_Problem" && "$(MAKE)" -f  "Easy_Sum_Set_Problem.mk" clean
