.PHONY: clean All

All:
	@echo "----------Building project:[ TomJerry - Debug ]----------"
	@cd "TomJerry" && "$(MAKE)" -f  "TomJerry.mk"
clean:
	@echo "----------Cleaning project:[ TomJerry - Debug ]----------"
	@cd "TomJerry" && "$(MAKE)" -f  "TomJerry.mk" clean
